<?php

$flyerData = [
    ["twilitesposter.jpg", "Twilites Flyer"],
    ["trolls-aldos.jpg", "The Trolls Flyer"],
    ["takedrugsfuck.jpg", "Take Drugs Flyer"],
    ["bignoiseposter.jpg", "Big Noise Flyer"],
    ["virus-reunion.jpg", "Virus Flyer"],
    ["stbooty1.jpg", "St Booty Flyer"],
    ["stbooty2.jpg", "St Booty Flyer"],
    ["stbooty3.jpg", "St Booty Flyer"],
    ["stbooty4.jpg", "St Booty Flyer"],
    ["stbooty5.jpg", "St Booty Flyer"],
    ["SpecialRedLightParty1.jpg", "Special Red Light Party Flyer"],
    ["WendellSRebelYBobaF.jpg", "Boba Fett Flyer"],
    ["cain-ox-pr-ainf.jpg", "CAIN Flyer"],
    ["samoans-poster.jpg", "The Samoans Flyer"],
    ["mrswhitehead.jpg", "Mrs Whitehead Flyer"],
    ["rambocob2.jpg", "Rambo Cob Flyer"],
    ["rambocob1.jpg", "Rambo Cob Flyer"],
    ["1973poster2.jpg", "1973 Flyer"],
    ["1973poster.jpg", "1973 Flyer"],
    ["kramdens.jpg", "The Kramdens Flyer"],
    ["maltbarleyposter.jpg", "Malt Barley Flyer"],
    ["shookybonesposter.jpg", "Shooky Bones Flyer"],
    ["bignoiseposter1.jpg", "Big Noise Flyer"],
    ["bignoiseposter2.jpg", "Big Noise Flyer"],
    ["bignoiseposter3.jpg", "Big Noise Flyer"],
    ["bignoiseposter4.jpg", "Big Noise Flyer"],
    ["bloodypony-poster1.jpg", "Blood Pony Flyer"],
    ["bloodypony-poster2.jpg", "Blood Pony Flyer"],
];
